resolver: nightly-2015-07-22
packages:
    - ./commonmark
    - ./commonmark-ast
    - ./commonmark-parser
    - ./commonmark-html
    - location: ./commonmark-testutils
      extra-dep: true

extra-deps:
    - html5-entity-0.2.0.3
