resolver: lts-15.0
packages:
    - ./comark
    - ./comark-syntax
    - ./comark-parser
    - ./comark-html
    - ./comark-testutils
extra-deps:
    - html5-entity-0.2.0.3
    - control-bool-0.2.1
    - cmark-0.5.6
    - dump-core-0.1.3
