name: comark-syntax
version: '0.1.0'
synopsis: Definitions of AST that represents a Commonmark (markdown) document.
description: See <https://github.com/zudov/haskell-comark#readme README>
category: Text
author: Konstantin Zudov
maintainer: co@zudov.me
copyright: (c) Konstantin Zudov, 2014, 2015, 2016, 2017
license: BSD3
default-extensions:
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- FlexibleInstances
- GeneralizedNewtypeDeriving
- OverloadedStrings
- LambdaCase
- ViewPatterns
dependencies:
- base >=4.7 && <5.0
- containers
- deepseq
- text
- elm-bridge
- aeson
library:
  source-dirs: src/
  ghc-options: -Wall -Werror
  exposed-modules:
  - Comark.Syntax
