name: commonmark
version: '0.1.0.0'
synopsis: Commonmark processing in pure haskell.
description: See https://github.com/zudov/haskell-commonmark#readme
category: Text
author: Konstantin Zudov
maintainer: co@zudov.me
copyright: (c) Konstantin Zudov, 2014, 2015, 2016
license: BSD3
dependencies:
  - base >=4.7 && <5
  - text

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - Text.Commonmark
  dependencies:
    - commonmark-ast
    - commonmark-parser
    - commonmark-html
executables:
  commonmark-hs:
    main: Main.hs
    source-dirs: ./.
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - commonmark
