name: commonmark-parser
version: '0.1.0.0'
synopsis: Parser for Commonmark (markdown)
description: See <https://github.com/zudov/haskell-commonmark#readme README>
category: Text
author: Konstantin Zudov
maintainer: co@zudov.me
copyright: (c) Konstantin Zudov, 2014, 2015, 2016
license: BSD3
dependencies:
- text
- commonmark-ast
library:
  source-dirs:
  - src/
  - extended/
  other-extensions:
  - OverloadedStrings
  - TupleSections
  - TupleSections
  - ViewPatterns
  - OverloadedStrings
  - LambdaCase
  - RecordWildCards
  ghc-options: -Wall
  exposed-modules:
  - Text.Commonmark.Parser
  - Text.Commonmark.Parser.Options
  dependencies:
  - base >=4.7 && <5.0
  - html5-entity >=0.2.0.1
  - control-bool
  - containers
  - transformers
tests:
  test:
    main: Main.hs
    source-dirs: tests/
    ghc-options: -Wall
    dependencies:
    - base >=4.7
    - hspec
    - syb
    - QuickCheck
    - deepseq
    - containers
    - commonmark-parser
    - commonmark-testutils
    - cmark
benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options: -O2
    dependencies:
    - base >=4.7 && <5
    - criterion
    - commonmark-testutils
    - commonmark-parser
    - deepseq
    - file-embed
