name: comark-testutils
version: '0.1.0.0'
synopsis: Some utilities for testing commonmark family of packages.
description: see README.md
category: Text
author: Konstantin Zudov
maintainer: co@zudov.me
copyright: (c) Konstantin Zudov, 2014, 2015, 2016
license: BSD3
extra-source-files:
- README.md
other-extensions:
- TemplateHaskell
- OverloadedStrings
- FlexibleInstances
dependencies:
- base >=4.7 && <5.0
- containers
- text
- cmark >=0.4.0.1
- aeson
- bytestring
- template-haskell
- comark-ast
- file-embed
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Text.Comark.TestUtils.CMark
  - Text.Comark.TestUtils.Spec
data-files:
- spec.json
